/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.ImageIcon;
import javax.swing.WindowConstants;

/**
 *
 * @author Jhon
 */
public class VentanaFinJuego extends javax.swing.JFrame {
    private int puntaje;

    /**
     * Creates new form VentanaFinJuego
     */
    public VentanaFinJuego() {
        initComponents();
        this.setLocationRelativeTo(null);
        setResizable(false);
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new ImageIcon("recursos/logo.png").getImage());
        
        lblPortadaFIn.setIcon(new ImageIcon("recursos/portadaFin.jpg"));
    }
    
    /**
     * Modifica la etiqueta con el Puntaje
     */
    public void setPuntaje(int puntaje){
        this.puntaje = puntaje;
        lblPuntajeNum.setText(String.valueOf(puntaje));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFinJuego = new javax.swing.JPanel();
        btnSalirJuego = new javax.swing.JButton();
        btnVlverMneu = new javax.swing.JButton();
        pnlPuntaje = new javax.swing.JPanel();
        lblPuntajeNum = new javax.swing.JLabel();
        lblFinJuego = new javax.swing.JLabel();
        lblPuntaje = new javax.swing.JLabel();
        lblPortadaFIn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sonic Laberinto");

        pnlFinJuego.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalirJuego.setBackground(new java.awt.Color(102, 102, 255));
        btnSalirJuego.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        btnSalirJuego.setText("Salir del Juego");
        btnSalirJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirJuegoActionPerformed(evt);
            }
        });
        pnlFinJuego.add(btnSalirJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, -1, -1));

        btnVlverMneu.setBackground(new java.awt.Color(102, 102, 255));
        btnVlverMneu.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        btnVlverMneu.setText("Volver al Menú");
        btnVlverMneu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVlverMneuActionPerformed(evt);
            }
        });
        pnlFinJuego.add(btnVlverMneu, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, -1, -1));

        pnlPuntaje.setBackground(new java.awt.Color(102, 102, 255));
        pnlPuntaje.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(153, 153, 153)));

        lblPuntajeNum.setBackground(new java.awt.Color(102, 204, 0));
        lblPuntajeNum.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 18)); // NOI18N
        lblPuntajeNum.setForeground(new java.awt.Color(255, 255, 255));
        lblPuntajeNum.setText("0");

        lblFinJuego.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 24)); // NOI18N
        lblFinJuego.setForeground(new java.awt.Color(255, 255, 0));
        lblFinJuego.setText("Fin del Juego");

        lblPuntaje.setBackground(new java.awt.Color(102, 204, 0));
        lblPuntaje.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 18)); // NOI18N
        lblPuntaje.setForeground(new java.awt.Color(255, 255, 255));
        lblPuntaje.setText("Tu Puntaje Fue:");

        javax.swing.GroupLayout pnlPuntajeLayout = new javax.swing.GroupLayout(pnlPuntaje);
        pnlPuntaje.setLayout(pnlPuntajeLayout);
        pnlPuntajeLayout.setHorizontalGroup(
            pnlPuntajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPuntajeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPuntaje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPuntajeNum)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPuntajeLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(lblFinJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        pnlPuntajeLayout.setVerticalGroup(
            pnlPuntajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPuntajeLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(lblFinJuego)
                .addGap(27, 27, 27)
                .addGroup(pnlPuntajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPuntaje)
                    .addComponent(lblPuntajeNum))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pnlFinJuego.add(pnlPuntaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 250, 100));
        pnlFinJuego.add(lblPortadaFIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 380));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFinJuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFinJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 372, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVlverMneuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVlverMneuActionPerformed
        // TODO add your handling code here:
        VentanaMenu ventanaMenu = new VentanaMenu();
        ventanaMenu.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btnVlverMneuActionPerformed

    private void btnSalirJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirJuegoActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirJuegoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaFinJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaFinJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaFinJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaFinJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaFinJuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalirJuego;
    private javax.swing.JButton btnVlverMneu;
    private javax.swing.JLabel lblFinJuego;
    private javax.swing.JLabel lblPortadaFIn;
    private javax.swing.JLabel lblPuntaje;
    private javax.swing.JLabel lblPuntajeNum;
    private javax.swing.JPanel pnlFinJuego;
    private javax.swing.JPanel pnlPuntaje;
    // End of variables declaration//GEN-END:variables
}
